### ISSUE TITLE
请问或许会讨论一些就业相关的信息吗

### ISSUE THREAD

**Issue by SibylGao** [GIS-Info/GIS-Info.github.io#6]
非常感谢前辈们的repo！！
但是我发现这个仓库更多是选校相关的，但是其实最近有很多关于找工作的困惑（不想转cs :(
想问下前辈们在国外找工作的一些经验，不胜感激！

**Comment by yeshancqcq** [comment]
欢迎关注我们的GISalon和Bilibili，里面有这方面的内容～

**Comment by peterliu502** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到了您的邮件。我将在阅读完您的邮件后，第一时间给您回复。

**Comment by peterliu502** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到了您的邮件。我将在阅读完您的邮件后，第一时间给您回复。

**Comment by SibylGao** [comment]
> 欢迎关注我们的GISalon和Bilibili，里面有这方面的内容～

非常感谢！
